# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-12-13 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualize', '0004_auto_20190510_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='json',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
