# Generated by Django 2.2.3 on 2019-07-10 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualize', '0004_auto_20190510_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Modified'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='sharing_groups',
            field=models.ManyToManyField(blank=True, editable=False, null=True, related_name='visualize_bookmark_related', to='auth.Group', verbose_name='Share with the following groups'),
        ),
    ]
