# Generated by Django 2.2.12 on 2020-08-26 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualize', '0005_bookmark_json'),
        ('visualize', '0006_auto_20190710_2310'),
    ]

    operations = [
    ]
