# Generated by Django 3.2.16 on 2022-11-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualize', '0010_auto_20221031_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlayer',
            name='wms_format',
            field=models.CharField(blank=True, default=None, help_text='most common: image/png. Only image types supported.', max_length=100, null=True, verbose_name='WMS Format'),
        ),
        migrations.AddField(
            model_name='userlayer',
            name='wms_styles',
            field=models.CharField(blank=True, default=None, help_text='pre-determined styles, if exist', max_length=255, null=True, verbose_name='WMS Styles'),
        ),
        migrations.AddField(
            model_name='userlayer',
            name='wms_version',
            field=models.CharField(blank=True, default=None, help_text='WMS Versioning - usually either 1.1.1 or 1.3.0', max_length=10, null=True),
        ),
    ]
