# Generated by Django 3.2.16 on 2023-07-03 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualize', '0011_auto_20221102_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlayer',
            name='password_protected',
            field=models.BooleanField(default=False, help_text='check this if the server requires a password to show layers'),
        ),
    ]
