SHOW_WATERMARK = False
DISCLAIMER_BUTTON_DEFAULT = False
USER_GEN_PREFIX = "User-Generated:"
USER_GEN_NOTICE = "Some content currently displayed was generated by users, not the Portal. Please review layer information in the 'Active' tab if you are unsure which information was user-generated."
ARCGIS_API_KEY = "set in local settings"